[project]
name = "eurybis"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.129.0",
    "uvicorn>=0.40.0",
    "uvloop>=0.22.1",
]

[dependency-groups]
dev = [
    "ruff>=0.15.1",
    "ty>=0.0.17",
]
